### ISSUE TITLE
Slide Deck from Re:Invent for SVS303

### ISSUE THREAD

**Issue by josephgps** [aws-samples/aws-saas-factory-serverless-workshop#2]
Hi Could you share the slide deck from SVS303 here? Thanks.

**Comment by sai7843** [comment]
Hello, during the workshop there was a promise to include instructions for destroying the resources created during the lab.  Any update on it?

**Comment by brtrvn** [comment]
Here are the slides from re:Invent 2019 SVS303

https://d1.awsstatic.com/events/reinvent/2019/REPEAT_1_Monolith_to_serverless_SaaS_A_hands-on_service_decomposition_SVS303-R1.pdf
