### ISSUE TITLE
Lab 2 Error on public-read ACL

### ISSUE THREAD

**Issue by farooq1234567** [aws-samples/aws-saas-factory-serverless-workshop#27]
Lab 2 errors out when running "sh website-lab2.sh" throwing a PutObject Access Denied when run with "--acl public-read".

If "Block Public Access" is disabled, the script works. This is not the recommended best practice for S3 buckets.

**Comment by brtrvn** [comment]
Resolved by 150d8c9fafdacb53f6224dc716869ccb48ee7de9
