### ISSUE TITLE
Base Structure for workshop

### ISSUE THREAD

**Issue by zidyia** [aws-samples/aws-saas-factory-serverless-workshop#3]
The manual assumes the account we are working on already have a pipeline provisioned where adding the repo will directly kick in the pipeline and build the stack, which is the case for people trying to do the workshop on their own.

Is there any document to show the base architect they started from ?

**Comment by 4patelr** [comment]
The project doesn't yet have all the artifacts to run this in your own account.  I heard it is coming soon.

**Comment by zidyia** [comment]
I was able to run lab1.template after building `aws-saas-factory-serverless-workshop/resources/custom-resources/` projects and uploading them to an S3 bucket as jar files .
