### ISSUE TITLE
Lab 2 npm audit vulnerabilities

### ISSUE THREAD

**Issue by szukalski** [aws-samples/aws-saas-factory-serverless-workshop#30]
During step 3 of Lab 2 (deploying the website), the npm package installation fails the audit so nothing gets installed (or built), resulting in no website behind CloudFront.

`89 vulnerabilities (38 moderate, 50 high, 1 critical)`

Can work-around by modifying website-lab2.sh to reference `npm install --audit=false` which is subjectively ok for a sample.

**Comment by brtrvn** [comment]
Updated all of the Node dependencies and resolved audit errors by providing specific resolutions to deprecated and out-of-date transient dependencies. Resolved with commit 783f4a55d123fc6de67092f1eb76a331cbb0b603.
