### ISSUE TITLE
Instructions to setup the Lab1 environment

### ISSUE THREAD

**Issue by PhoduCoder** [aws-samples/aws-saas-factory-serverless-workshop#6]
I am referring to the instructions for Lab1. It looks like that the instructions in the Readme assumes a lot of steps with the environment setup. Can we verify on what all steps should someone execute while trying the Lab1 in their AWS account and also for the subsequent labs.
As an example, there are multiple bash scripts and CF templates in the resources folder, do we need to run them in any definite order?

**Comment by 4patelr** [comment]
Hi,

You first need to build the Java projects under resources/custom-resources/ and upload the jar files to a S3 bucket that you will use for running the lab1.template.

**Comment by brtrvn** [comment]
Self-service instructions added to the README in commit ce7221dd374a426a5ca3d0cec2905c30b74bef67
